version: '3.8'

services:

    flask-backend:
        build: ./backend
        container_name: back
        hostname: back
        networks:
            net:
                ipv4_address: 192.168.2.10
        cap_add:
            - NET_ADMIN
        volumes:
            - ./dockerDB/DockerDB.db:/app/instance/DockerDB.db

    vue-frontend-nginx:
        build: ./frontend
        container_name: front-ng
        volumes:
            - ssl:/etc/nginx/ssl/
        hostname: front-ng
        ports:
            - 443:443
            # - 80:80
        networks:
            net:    
                ipv4_address: 192.168.2.11
        cap_add:
            - NET_ADMIN

networks:
  net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.2.0/24"
volumes:
  ssl:
    external: true

