version: '3.8'

services:
    flask-backend:
        build: ./backend
        ports: 
            - 5000:5000
        env_file:
            - ./backend/.env
            - ./backend/.flaskenv # Path to your .env file

    vue-frontend:
        build: ./frontend
        ports: 
            - 3000:5000
        env_file:
            - ./frontend/.env # Path to your .env file