version: '3.8'

services:

    flask-backend:
        build: ./backend
        ports: 
            - 8084:8084
            

    vue-frontend:
        build: ./frontend
        ports: 
            - 8083:8083
